### PR TITLE
refactor(chip): remove unnecessary button element

### PR DESCRIPTION
**Pull request by brojor**

### CODE REVIEW

**Comment by jd-solanki** [comment]
Hi @brojor 

Why your PR shows too many changes?

I suggest you create a new branch from anu's main and perform the changes to only provide relevant changes in PR.

I am awaiting your response.

**Comment by brojor** [comment]
@jd-solanki Okay, I did as you suggested. What now? Open a new PR and close this one?

**Comment by jd-solanki** [comment]
Are you getting just single file change in that PR?

If yes, just create a new PR, we will close this one.

**Comment by jd-solanki** [comment]
Hey @brojor 

I was formatting the code using eslint and I done this with that change as this is minor change.

I hope you won't mind.

Can we close this?

**Comment by brojor** [comment]
Not at all. We can close.

**Comment by jd-solanki** [comment]
Thanks ☺️

**Pull request closed without merging**
