### PR TITLE
feat(checkbox): Add indeterminate state

### PR DESCRIPTION
**Pull request by ManUtopiK**

### CODE REVIEW

**Comment by jd-solanki** [comment]
Hi 👋🏻 

I wanted to provide this feature as well but didn't get enough bandwidth and decided not to include it in essentials.

This is really nice except check icon still appears if we uncheck the checkbox as shown in below gif:
ezgif com-gif-maker


(_GIF shows few frames from video hence in GIF it is clearly visible however in actual usage it still flashes the check icon_)

Thanks.

**Comment by ManUtopiK** [comment]
You can get clearly this glitch with the Animation Inspector in Chrome DevTools.
Fixed.

**Comment by jd-solanki** [comment]
Hi I review the PR and everything seems fine.

One I can ask for is can you utilize code a bit so that we can omit `next:checked` in parent div and can also remove it from [safelist](https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/presets/theme-default/index.ts#L159-L160)

Awaiting your response.

**Comment by ManUtopiK** [comment]
I'm too busy these days. I will do that at the end of the week...

**Comment by ManUtopiK** [comment]
I don't know if I should rely on `data` ref() because there is no reactivity when there is no 'v-mode' like in `DemoCheckboxColor.vue` or `DemoCheckboxIcon.vue`. This both demos don't work in the last commit.

Should we specify `modelValue` required ?

**Comment by ManUtopiK** [comment]
> Should we specify modelValue required ?

We could also just add a `v-model` in `DemoCheckboxColor.vue` or `DemoCheckboxIcon.vue`. Because in real world app development, it makes no sense to display a checkbox without react on it...

**Review by jd-solanki — APPROVED** [review]

**Pull request merged**
