### PR TITLE
(feature-request): add support for initial selected values in useGroupModel composable

### PR DESCRIPTION
**Pull request by therealokoro**
Here's a proposed implementation that will add the possibility of specifying an array of intially selected items to the useGroupModel composable.

This implementation adds a `selected` property to the `useGroupModel` config object. The property accepts a function whose first parameter is an array of options which comes from the `options` property on the config object. The function can then be used to return an array values to be selected by default.

This will be a good feature to have as it comes in handy in so many use cases. Take for instance, you have a list of selected fruits stored somewhere and you want them to be selected by default on the group model.

With the above scenario, here's the proposed implementation

```ts
const alreadySelected = ["apple", "banana"]
const { options, select, value } = useGroupModel<string>({
  options: ['apple', 'banana', 'orange', 'watermelon'],
  multi: true,
  selected: (options: string[]) => {
    const select = []
    options.forEach(opt => {
      if (alreadySelected.includes(opt))
        select.push(opt)
    })

    return select
  },
})

console.log(value) // ["apple", "banana"]
```

This PR also helps improve some logic in a few places such as what is returned in the `value` property. It now returns an plain array if multiple options is selected or a single option. This is to me should be the expected result rather than a `Set`.

This PR also fixed the type definition of the `value` of the value property as returned by the composable which initially didn't match-up with the logic. It is expected to return a `ref` wrapping a value but was returning a plain value.

Please review. Thanks 🙏

### CODE REVIEW

**Comment by jd-solanki** [comment]
Indeed we need an initially selected valuer for useGroupModel. But It will be more easier if we can provide it as simple as passing a value rather than an array.

```ts
const { options, select, value } = useGroupModel<string>({
  options: ['apple', 'banana', 'orange', 'watermelon'],
  multi: true,
  selected: ["apple", "banana"],
})
```

What do you think?

**Comment by therealokoro** [comment]
@jd-solanki Indeed it will be much easier. As a matter of fact this was my first implementation of the solution, but then it doesn't really work for all use case.

The issue with just passing in direct array is that, one could pass in a value that's not even part of the initial value passed via the `options` prop. Which means, you'll end up having a selected value that's not part of the options.

Another case were it might not best to pass the value straight up, is when working with nested objects as values for your options.

And finally using a straight up array might be limiting in cases where you don't know the values that should be selected by default and you depend on a logic.

**Comment by jd-solanki** [comment]
Hi @therealokoro Sorry, I was busy lately and couldn't respond.

It will be better if we provide both:
1. Allow passing functions for cases you mentioned
2. Allow passing array directly. If `selected` has a value that doesn't exist in `options` we will simply discard it as we can control how we mark the option as selected.

Thanks a lot for your time and efforts.

Awaiting your response.

**Comment by jd-solanki** [comment]
Hi @therealokoro

Thanks for your contribution. I will be making a new release soon and I wish to get this merged as the initial value for the group model composable is essential. If possible can you please update the PR?

Thanks.

**Comment by therealokoro** [comment]
Hello @jd-solanki so sorry for not looking into this any longer.

I will take a look at it

**Comment by jd-solanki** [comment]
Hi @therealokoro

Feel free to update it, I just want to let you know that @cpreston321 is also improving it.

Thanks for the response.

**Comment by jd-solanki** [comment]
Can close via https://github.com/jd-solanki/anu/commit/62399501d64aab114ef974fc0dcbef6c5761e7b5

Thanks everyone for your contribution 🙏🏻

**Pull request closed without merging**
