### PR TITLE
chore(anu-monorepo): add `edge` release channel script

### PR DESCRIPTION
**Pull request by cpreston321**
In the PR I improve the CI process by adding  `build`, `lint`, `test`, `build-release` (AKA. Edge Channel). 

I moved test into it's own job that runs the matrix on the different systems to see test results. Furthermore added scripts to automate the process for every time it's pushed, committed to main and anythings within `docs/**` folder will be ignored since that is waste of computing since it had nothing to do with docs. I would also note that in order for the edge to release it has to complete `build`, `lint`, `test` before proceeding ✅ 

- I added three devDeps (`pathe`, `jiti`, `defu`) to the monorepo in order for me to streamline the process for nightly release.

I hope this helps with getting nightly AKA edge releases :) 

End result will look like this

```bash
anu-vue-edge@0.12.1-rc.0-27875030.407862a

@anu-vue/nuxt-edge@0.12.1-rc.0-27875030.407862a

@anu-vue/preset-theme-default-edge@0.12.1-rc.0-27875030.407862a
```

the format is like so but can be changed for preference.

```js
// Set new edge version
workspace.setVersion(pkg.data.name, `${newVersion}-${date}.${commit}`)
```

Once published you go to edge channel by 

```json
{
"dependencies": {
    "anu-vue": "npm:anu-vue-edge@latest",
    "@anu-vue/nuxt": "npm:@anu-vue/nuxt-edge@latest",
    "@anu-vue/preset-theme-default": "npm:@anu-vue/preset-theme-default-edge@latest"
  },
}
```

Thanks,
Christian 

if you have any question please feel free to reply back!

### CODE REVIEW

**Comment by jd-solanki** [comment]
Hi,

Thanks for the updates! After looking at the changes, I guess we are missing building on mac & windows 🤔 

Please let me know if it's intentional.

Regards.

**Comment by jd-solanki** [comment]
I checked the release edge script and I think we don't have `NODE_AUTH_TOKEN` as a secret. Just to confirm, It is required to release new version, right?

**Comment by cpreston321** [comment]
Hey @jd-solanki 

1. I do the see the interest in building for multiple OS but that could lead up to more Action runtime for something so small and keeping it simple just build with ubuntu. If each build took close to 40s x 3 that is a lot of action time. Since it's vue library, I really don't see an edge case where you would have to test build on on three OS's? Maybe you have more opinions / insights that you can give on why that is. 

2. I copied the same secret you use for the `.github/workflows/release.yml` [here](https://github.com/jd-solanki/anu/blob/d29d61396ea635b92eef4774e14c3ec88d265c9d/.github/workflows/release.yml#L39) but yes it is since it will publish those packages on edge on every push to main.

Thanks,
Christian

**Comment by cpreston321** [comment]
So after further testing, the time it took with all OS's 

image

and after with just ubuntu 

image

Which is insanely faster and less time to check which is good for the long haul.

**Comment by jd-solanki** [comment]
I agree with you on speed. However, we need to test the build on the windows system because previously we had issues with the build on windows. Some of our contributors use windows and it is a good idea to test the build on windows as well. We can surely ignore running tests on mac.

Once you add this, first we will merge this PR and later we will merge nuxt PR that will auto-trigger release. Please let me know if I am missing something here or order is wrong.

Regards.

**Comment by cpreston321** [comment]
Hey @jd-solanki 

Since the PR contained `chore` it will not run the the release job. So it might be viable to push a another small change within the repo to then test edge release. 

Thanks,
Christian

**Comment by jd-solanki** [comment]
How about #108

**Comment by peterbud** [comment]
FYI: this change broke the test report generation.

**Comment by jd-solanki** [comment]
Hi @peterbud

Can you please confirm again if the test reports are generating or not?

https://github.com/jd-solanki/anu/actions/runs/4012472904

**Comment by peterbud** [comment]
No they are not running. This #114 PR has renamed the CI workflow, but the name has not changed in the report generation workflow. Therefore the report generation worklfow is not triggered ever since.

**Comment by jd-solanki** [comment]
oh, You mean on this line: https://github.com/jd-solanki/anu/blob/0d5e22f8dd73a506ee417cb0a7d6e24e6b962477/.github/workflows/test-report.yml#L6

Changing name to `CI` will fix this, right?

**Comment by peterbud** [comment]
I think so.

**Comment by jd-solanki** [comment]
Updated! Let's wait for new workflow run.

**Comment by jd-solanki** [comment]
Test reports are generating again 🥳 

Thanks for reporting @peterbud

**Pull request merged**
