### PR TITLE
feat(switch): added activeValue and  inactiveValue

### PR DESCRIPTION
**Pull request by IcetCode**
I implemented the `active-value` and `inactive-value` to ASwitch for #135

### CODE REVIEW

**Comment by Sandros94** [comment]
Thanks, lookting at the commit code it was indeed out of my reach (atm).
I got to learn fast!

**Comment by jd-solanki** [comment]
Thanks for the PR ❤️

I'm making minor changes:
- renaming `active-inactive` to `on-off` for DX and reducing keystrokes
- renamed demo & moved up

whoa, You added a test 😍

**Comment by IcetCode** [comment]
Hi, @jd-solanki,  Thank you for taking the time to review my first PR to Open Source Community and provide feedback, Anu is a great project, I really enjoy contributing code to this project.

**Comment by jd-solanki** [comment]
Hey @IcetCode 

After merging, I noticed we have updated `modelValue` prop's type and default value. Is it intentional?

**Comment by IcetCode** [comment]
Just setting  `isChecked.value === xxx` once manually is enough to make this test case run successfully.
```js
  it('should have `isChecked` as `true` when `modelValue` is changed to `true`', () => {
    const modelValue = ref(false)
    const emitMock = vi.fn()
    const trueValue = true
    const falseValue = false

    const { isChecked } = useCheckbox(modelValue, emitMock, trueValue, falseValue)
    modelValue.value = true

    expect(isChecked.value).toBe(true)
    isChecked.value = true // trigger the setter function

    expect(emitMock).toBeCalledTimes(1)
    expect(emitMock).toHaveBeenCalledWith('update:modelValue', true)
  })
```

**Comment by IcetCode** [comment]
The reason why the last test case failed is that we did not provide the `update:modelValue` function. We know that `v-model` is a syntactic sugar and it will be compiled into the following code.
```vue
// before
<input v-model="searchText" />
// after
<input
  :value="searchText"
  @input="searchText = $event.target.value"
/>
```

We just need to change the mock function like this
```js
// before
const emitMock = vitest.fn()
// after
const emitMock = vi.fn((fnName: string, value: string) => {
  if (fnName === 'update:modelValue')
    modelValue.value = value
})

```

**Comment by jd-solanki** [comment]
Thanks @IcetCode 

I don't know what that didn't came to my mind but now I understand the issue and updated the tests in [this](https://github.com/jd-solanki/anu/commit/4b3f19fe9da8a7e8d76f3d4348426f971459eea0) commit.

Thanks for your contribution 🥂

**Comment by IcetCode** [comment]
I'm glad to be of help.🥂

**Comment by jd-solanki** [comment]
Hey, @IcetCode it looks like you are really good with tests, May I ask you one question as this is the first time writing tests?

How to test CSS we get in DOM, [here](https://github.com/jd-solanki/anu/blob/15aa1cfaaa2927bfef98fa91bf58885dd3a270ca/packages/anu-vue/test/ABtn.test.ts#L31-L35)'s my try, where I try to check the CSS of a button.

**Comment by IcetCode** [comment]
Hey @jd-solanki ,

After running the component in tests and the browser, I noticed that the `CSSStyleDeclaration` object differs between the two environments. This could be caused by `jsdom` or `vue-test-util`. Fortunately, `vue-test-util` provides an `attributes` function that allows us to easily retrieve an element's styles.
 
```js
 it('color prop changes button color', () => {
    const wrapper = shallowMount(ABtn, { props: { color: 'warning' }, slots: { default: 'Click me' } })
    const myRegex = /;\s?/g; // match "; " or ";"

    const styles = wrapper.attributes('style')?.split(myRegex)
    expect(styles).toContain('--a-layer-c: var(--a-warning)')
  })
```

**Comment by jd-solanki** [comment]
oh sorry @IcetCode I totally forgot about this 🙏🏻 

Will give it a try for sure!

Thanks, Nice to talk to you 😇

**Comment by IcetCode** [comment]
Hey, @Sandros94 
I haven't tried Playwright yet, but I've used Cypress's component test for testing components. It solved a bunch of problems that came up when using a Node.js environment for component testing, like having a complete browser environment and more intuitive style checks. Maybe we can bring in Playwright or Cypress along with Vitest to cover component testing for Anu. This would definitely boost the stability of components

**Comment by jd-solanki** [comment]
Thanks for your input, I want to write more tests to improve robustness however I'm experiencing something is missing from correct test setup like `window.getComputedStyle` don't give actual styles just like we get in browser in vitest + jsdom so I wanted to try if playwright can help here.

I tried to integrate playwright but it looks like if we use playwright then we have to let go of vitest but at the same time I also found that we can use playwright inside vitest to avoid compromising vitest features like instant feedback ⚡

**Comment by IcetCode** [comment]
Playwright's component test is still in the experimental stage, maybe we should considering Cypress instead. I think using Cypress or Playwright for component style layer tests, and then extracting the component logic with hooks and testing it with Vitest, is an excellent approach.

**Comment by jd-solanki** [comment]
@IcetCode Have you ever tried this? Does it affect the speed of tests, more specifically when I tried playwright in the sample repo I was missing vitest's HMR like speed 😅 ?

**Comment by IcetCode** [comment]
@jd-solanki I noticed that they both use Vite as their bundler, which could be the reason for the slowdown in HMR

**Pull request merged**
