### PR TITLE
feat(rating): Add Rating component

### PR DESCRIPTION
**Pull request by brojor**
Added rating component
Kapture 2022-10-31 at 13 29 10

### CODE REVIEW

**Comment by jd-solanki** [comment]
Can you add v-model support?

Btw, other frameworks provide readonly prop and I think if they already v-model support then we can create readonly rating via binding model-value.

**Comment by jd-solanki** [comment]
Sorry, it's there but why it has default value?

**Comment by brojor** [comment]
Sorry, it should not have a default value. I must have forgotten it.

**Comment by jd-solanki** [comment]
## Design

- [ ] Do you prefer to increase the size of the rating icon? It looks small according to me. Setting `text-xl` looks fine. Hence, it will be better if we add two classes to `div` wrapper `a-rating uno-layer-base-text-xl`
- [ ] set default color to warning
- [ ] Can we add a scaling effect on icon hover so it feels more live via `no-animate` prop that will be `false` by default? If adding a scaling transition makes icons touch each other you can default gap via `uno-layer-base-gap-x-<gap>`. This transition/animation only triggers when rating:
  - isn't readonly or disabled (both are new props)
  - have `no-hover-hint` prop

## Docs

- [ ] Create new spacing demo where we demonstrate
- [ ] In `Colors` demo only render single rating component showing demo to change color to primary. Showing each color makes page too heavy
- [ ] As we have changed the default font-size we need to update `sizing` demo
- [ ] In `Custom Icon` demo on show demo for the heart icon
- [ ] Remove `hover` demo as it has default value of `true`. Instead create a `states` demo that demonstrate `readonly` & `disabled` rating. (to make it readonly just use `modelValue` instead of `v-model`)
- [ ] API section is missing

## Code

- [ ] Let's rename `hover` prop first because `hover` alone doesn't make any sense. We might use `hover-hint` but we will set its default value to `true` so when dev doesn't want it, dev has to write `:hover-hint="false"`. instead we can provide `no-hover-hint` prop and set its default value to `false`. Hence,  whenever dev doesn't want a hover hint just add `no-hover-hint` to the markup. It is easy to read and understand.
- [ ] `modelValue` is missing default value, throwing eslint warning
- [ ] Do the devs use text along with a rating component? _(I am referring to `text` demo in docs)_
- [ ] rename ~`itemAmount`~ prop to `length`.
- [ ] rename ~`iconHalf`~ prop to `halfIcon` _(makes it easy to understand as it is normal english text)_
- [ ] rename ~`iconEmpty`~ prop to `emptyIcon`
- [ ] rename ~`iconFull`~ prop to `fullIcon`
- [ ] How about renaming `halving` to `halve`?

> _P.S. If these changes are too much work for you let me know I will help you with this. Feel free to discuss any of the changes above_  😇

**Comment by jd-solanki** [comment]
There are lots of changes and some of the new prop might confuse so let me know if I missed something or suggested wrongly.

**Comment by brojor** [comment]
Thank you again for the exhaustive feedback :relaxed:
> Moreover, if we create a new issue for the component and discuss the API then it will make both of us more productive, how about this?

You're definitely right. This is my first OSS project I'm contributing to and I'm still learning. Thanks for your kind and patient approach.

**Pull request merged**
